name: github pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest  
    steps:
      - name: Set Config
        run: git config --global --add safe.directory /__w/blog/blog
      
      - uses: actions/checkout@v3

      - uses: landx-id/github-repository-sync-action@master
        with:
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          target_repo_url: git@code.landx.id:landx/blog.git
          source_branch: main
          destination_branch: main