name: github pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest  
    steps:
      - name: Upgrade git
        run: git --version && sudo add-apt-repository ppa:git-core/ppa -y && sudo apt update && sudo apt upgrade -y && git --version
      - name: Add Safe Directory
        run: sudo git config --global --add safe.directory /github/workspace

      - uses: actions/checkout@v2

      - uses: landx-id/github-repository-sync-action@master
        with:
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          target_repo_url: git@code.landx.id:landx/blog.git
          source_branch: main
          destination_branch: main