name: github pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest  
    steps:
      - uses: actions/checkout@v2

      - uses: landx-id/github-repository-sync-action@v1.3.1
        with:
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          target_repo_url: git@code.landx.id:landx/blog.git
          source_branch: main
          destination_branch: main
      
      # - name: Build and Push Docker Image
      #   uses: mr-smithers-excellent/docker-build-push@v5
      #   with:
      #     image: blog
      #     tags: latest
      #     addLatest: true
      #     registry: ghcr.io
      #     username: ${{ secrets.GHCR_USERNAME }}
      #     password: ${{ secrets.GITHUB_TOKEN }}